### PR TITLE
Add an option to generate .gitignore file

### PR DESCRIPTION
**Pull request by kevinjqiu**

### CODE REVIEW

**Comment by juanpabloaj** [comment]
@kevinjqiu thanks for your PR

a commentary, when I try the new changes, and in the gitignore I press `enter` the gitginore is not created

``` bash
$ pip-init
name (temp):
version (0.1.0):
description (A pip package):
license (MIT):
author (JuanPablo):
Generate .gitignore file [Y/n]? <here I press ENTER>
$ ls -a
.  ..  setup.py
```

when I see `[Y/n]`, I think the default option is Yes, if I press `enter` I get the default option, but the `.gitignore` file is not created.

what do you think about this ?

**Comment by kevinjqiu** [comment]
@juanpabloaj I think it's a good and reasonable suggestion. I'll update this PR shortly :)

**Comment by kevinjqiu** [comment]
@juanpabloaj Updated.

**Comment by juanpabloaj** [comment]
other thing, I really like you refactor commit @7bf7657. 

but, is necessary create a gitignore file? is this case maybe is necessary create the `REAME.md` file too. (and so on ... requirements.txt file, etc)

for create the full structure of a python package exist https://github.com/audreyr/cookiecutter

I don't know if is necessary create the gitignore,  or maybe set no as the default option [y/N], what do you think ?

**Comment by kevinjqiu** [comment]
@juanpabloaj I did use cookiecutter on some projects, but sometimes I don't need the full project skeleton that many cookiecutters provide, and I prefer just have a simple `setup.py` and a couple of other essential files, gitignore being one of them for most devs nowadays as version control is so integrated into our daily lives :)

I could default it to "No" though.

**Comment by juanpabloaj** [comment]
@kevinjqiu I made the merge, thanks .

If in the future the gitingore is innecesary we can change the default option to "No"

**Comment by kevinjqiu** [comment]
Sounds good.  Cheers.

**Comment by juanpabloaj** [comment]
with your changes I uploaded the version 0.3.0 to pypi :dancers:

**Pull request merged**
